baseURL = "https://battiato.dev"
languageCode = "en-us"
title = "Riccardo Battiato"
theme = "ink"
paginate = 10

copyright = "© Riccardo Battiato. All rights reserved"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# googleAnalytics = "UA-123-45"

[params]
	subtitle = "Frontend Developer"

	# Optional 64x64 avatar image.
	# avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Projects"
url = "/projects"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/_rbattiato"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/rbattiato"

[taxonomies]
   tag = "tags"
